stages:
  - build
  - test
  - publish

default:
  image: python:3.10
  cache:
    key:
      files:
        - setup.cfg
    paths:
      - .pip/

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

# Build package
build:
  stage: build
  artifacts:
    paths:
      - dist/
  before_script:
    - pip install build
  script:
    - python -m build

# Run unit tests
test-unit:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
      - SQLALCHEMY_VERSION:
          - '1.4'
          - '2.0'
  image: python:${PYTHON_VERSION}
  artifacts:
    when: always
    reports:
      junit: reports/pytest_*.xml
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage.xml
  coverage: '/TOTAL .* (\d+%)/'
  before_script:
    - pip install --upgrade pip tox
    - pip install SQLAlchemy~=${SQLALCHEMY_VERSION}
  script:
    # Run tests using tox with the package that was built in the build stage
    - tox run --installpkg dist/*.whl -e clean,py,flake8,report -- --junit-xml=reports/pytest_${PYTHON_VERSION}.xml

# Publish package
publish:
  stage: publish
  rules:
    # Only publish when a tag is created
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install twine
    - export TWINE_USERNAME=gitlab-ci-token
    - export TWINE_PASSWORD=${CI_JOB_TOKEN}
  script:
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
