[tox]
minversion = 4.5.1
envlist = clean,py{310,311,312,313,314}-sqlalchemy{1.4,2.0},report,flake8,mypy
skip_missing_interpreters = true

[flake8]
max-line-length = 140
exclude = _version.py
ignore =
per-file-ignores =
    # False positives for "unused imports" in __init__.py
    __init__.py: F401

[testenv]
extras = testing
commands = python -m pytest --cov --cov-append {posargs}

# TODO: 0.12.0 is not released yet. For testing we need to build and install validataclass manually.
# TODO: (In the validataclass repo, run `make build`. Then copy the resulting .whl file to _tmp.)
deps =
    ./_tmp/validataclass-0.12.0a1.dev1-py3-none-any.whl

[testenv:flake8]
commands = flake8 src/ tests/

[testenv:mypy,py{310,311,312,313,314}-mypy]
commands = mypy {posargs}

[testenv:mypy-debug]
# Use no-incremental to disable mypy caching when developing the mypy plugin
commands = mypy --show-traceback --no-incremental {posargs}

[testenv:clean]
commands = coverage erase

[testenv:report,py{310,311,312,313,314}-report]
commands =
    coverage html
    coverage xml
    # TODO: As soon as we've reached 100% test coverage, enforce this test coverage.
    # coverage report --fail-under=100
    coverage report

[testenv:sqlalchemy1.4]
set_env = PIP_CONSTRAINT=constraints.sqlalchemy1.4.txt

[testenv:sqlalchemy2.0]
set_env = PIP_CONSTRAINT=constraints.sqlalchemy2.0.txt
