[tox]
requires = tox >= 4.32
envlist = clean, py3{10-14}-sqlalchemy{1.4,2.0}, report, flake8, mypy
skip_missing_interpreters = true

[flake8]
max-line-length = 120
exclude = _version.py
ignore =

[testenv]
# Build and install a wheel (speeds up tox runs)
package = wheel
wheel_build_env = .pkg

# Install all testing requirements by default(pytest, mypy etc.)
extras = testing

# Default command: Run pytest
commands = python -m pytest --cov --cov-append {posargs}

# Conditionally install SQLAlchemy version depending on the sqlalchemy factor
constrain_package_deps = true
deps =
    sqlalchemy1.4: sqlalchemy >= 1.4, < 2.0
    sqlalchemy2.0: sqlalchemy >= 2.0, < 2.1

[testenv:flake8]
commands = flake8 src/ tests/

[testenv:mypy, py3{10-14}-mypy]
commands = mypy {posargs}

[testenv:mypy-debug]
# Use no-incremental to disable mypy caching when developing the mypy plugin
commands = mypy --show-traceback --no-incremental {posargs}

[testenv:clean]
commands = coverage erase

[testenv:report, py3{10-14}-report]
commands =
    coverage html
    # TODO: As soon as we've reached 100% test coverage, enforce this test coverage.
    # coverage report --fail-under=100
    coverage report
